version: '3.8'

services:
  # Development application service
  letsdraw-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: letsdraw-dev
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - TIMER=${TIMER:-300}
      - CANVAS_WIDTH=${CANVAS_WIDTH:-3800}
      - CANVAS_HEIGHT=${CANVAS_HEIGHT:-2000}
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS:-15000}
      - RATE_LIMIT_MAX_REQUESTS=${RATE_LIMIT_MAX_REQUESTS:-1000}
      - CORS_ORIGIN=${CORS_ORIGIN:-*}
      - HELMET_ENABLED=${HELMET_ENABLED:-false}
    depends_on: []
    networks:
      - letsdraw-dev-network
    volumes:
      - .:/app
      - /app/node_modules
      - dev-logs:/app/logs
    command: npm run dev

networks:
  letsdraw-dev-network:
    driver: bridge

volumes:
  dev-logs:
    driver: local